# Generated by Django 3.2.7 on 2021-10-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Confirmation', models.DateField()),
                ('County_Living', models.TextField(max_length=20)),
                ('Gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('Imported', models.BooleanField()),
                ('Age_Group', models.TextField()),
                ('Number_of_Confirmed_Cases', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('Date_Reported', models.DateField(primary_key=True, serialize=False)),
                ('Reported_Covid19', models.IntegerField()),
                ('Reported_Home_Quarantine', models.IntegerField()),
                ('Reported_Enhanced_Surveillance', models.IntegerField()),
                ('Total_Reported', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Brand', models.CharField(max_length=20)),
                ('First_Dose_Daily', models.IntegerField()),
                ('Second_Dose_Daily', models.IntegerField()),
                ('Total_Vaccinated_Daily', models.IntegerField()),
            ],
        ),
    ]
