# Generated by Django 3.2.7 on 2021-10-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211019_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Suspect',
        ),
        migrations.DeleteModel(
            name='Vaccination',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
